### ISSUE TITLE
Registration and Login Activities

### ISSUE THREAD

**Issue by GROX13** [AdMove/android-admove-old#6]
ახალი მომხმარებლების რეგისტრაცია ჩვენს აპლიკაციაში. რეგისტრაცია ასევე შესაძლებელი უნდა იყოს Facebook-ის და Google+ ის ექაუნთებით.

**Comment by toka16** [comment]
Facebook და Google+ მუშაობს, რეგისტრაცია დასამატებელია

**Comment by GROX13** [comment]
რეგისტრაციის გვერდი დამატებულია. ვიზუალი შეცვლილია Facebook და Google+ ის ღილაკები დასამატებელია Login-ის გვერდზე.
